### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ingrid88** [mccraveiro/mongoose-migration#9]
In node.js express project folder
➤ migrate init                                                                                    
```/usr/local/bin/migrate: line 1: use strict: command not found```
```/usr/local/bin/migrate: line 3: syntax error near unexpected token `('```
```/usr/local/bin/migrate: line 3: `var program = require('commander');'```

**Comment by mccraveiro** [comment]
I reverted the pull request that introduced bugs. The package should be working now. 
I am sorry it took so long.
